[package]
name = "yt-bevy-labs-2d-depth"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "938d810", features = [
    "file_watcher",
] }
